Adds note about enabling long path support on Windows (#215)
This PR adds a note about enabling long path support on Windows to avoid
PIP installation issues:

E.g.:

```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '...deps\\py\\numpy\\numpy-1.23.5-cp310-cp310-win_amd64\\numpy\\.libs\\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths
```

![image](https://github.com/user-attachments/assets/9a5fa0db-99c9-456f-aa94-05e59a8dfec7)