Removes the rsl_rl agent configs from multi-agent tasks (#116)
# Description

This PR removes the `rsl_rl` agent configs from multi-agent tasks so
avoid the following known issue:

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/horde/IsaacLab-Internal/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/hydra.py", line 91, in hydra_main
    func(env_cfg, agent_cfg, *args, **kwargs)
  File "/home/horde/IsaacLab-Internal/source/standalone/workflows/rsl_rl/train.py", line 117, in main
    runner = OnPolicyRunner(env, agent_cfg.to_dict(), log_dir=log_dir, device=agent_cfg.device)
  File "/home/horde/miniconda/envs/isaaclab/lib/python3.10/site-packages/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()
  File "/home/horde/IsaacLab-Internal/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 145, in get_observations
    obs_dict = self.unwrapped._get_observations()
  File "/home/horde/IsaacLab-Internal/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/direct_rl_env.py", line 580, in _get_observations
    raise NotImplementedError(f"Please implement the '_get_observations' method for {self.__class__.__name__}.")
NotImplementedError: Please implement the '_get_observations' method for Env.
```

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

## Checklist

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with
`./isaaclab.sh --format`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] I have updated the changelog and the corresponding version in the
extension's `config/extension.toml` file
- [x] I have added my name to the `CONTRIBUTORS.md` or my name already
exists there